[www]
user  = www-data
group = www-data

listen = 127.0.0.1:9000

pm                   = dynamic
pm.max_children      = 20
pm.start_servers     = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 10

; Write stdout/stderr to Docker log collector
access.log  = /proc/self/fd/2
php_flag[display_errors] = off
