CREATE TABLE IF NOT EXISTS `classrooms` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `class_code` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `class_name` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `class_title` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `teacher_id` int unsigned NOT NULL,
  `student_id` int unsigned NOT NULL,
  `status` enum('Active','Inactive') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Active',
  `created_by` int unsigned NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `class_code` (`class_code`),
  KEY `teacher_id` (`teacher_id`),
  KEY `student_id` (`student_id`),
  KEY `status` (`status`),
  KEY `created_at` (`created_at`),
  KEY `class_name` (`class_name`),
  KEY `class_title` (`class_title`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
